# Generated by Django 4.0.4 on 2022-05-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_remove_recipes_ingredients_recipes_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
