# Generated by Django 4.0.4 on 2022-05-25 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_alter_recipes_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='ingredient_recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.ingredient')),
                ('measureunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.measureunit')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.recipes')),
            ],
        ),
    ]
