# Generated by Django 4.0.4 on 2022-05-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_measureunit_remove_recipes_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(through='bookapp.Ingredient_Recipe', to='bookapp.ingredient'),
        ),
    ]
