# Generated by Django 4.0.4 on 2022-05-25 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_recipes_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_recipe',
            name='ingredient',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bookapp.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient_recipe',
            name='recipe',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bookapp.recipes'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient_recipe',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
