# Generated by Django 4.0.4 on 2022-05-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_alter_ingredient_recipe_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
