# Generated by Django 4.0.4 on 2022-05-27 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_alter_recipes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_recipe',
            name='ingredient',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='sostav', to='bookapp.ingredient'),
        ),
    ]
