# Generated by Django 4.0.4 on 2022-05-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_alter_ingredient_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient_recipe',
            old_name='count',
            new_name='value',
        ),
    ]
