# Generated by Django 4.0.4 on 2022-05-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0011_alter_recipes_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='bookapp.Ingredient_Recipe', to='bookapp.ingredient'),
        ),
    ]
