# Generated by Django 4.0.5 on 2022-06-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0012_alter_recipes_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='create',
        ),
    ]
