# Generated by Django 4.0.5 on 2022-06-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0013_remove_recipes_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='update',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='update',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
